apiVersion: v1
kind: Service
metadata:
  name: teemii-frontend
  namespace: teemii
spec:
  type: NodePort
  selector:
    app: teemii-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  