apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-pod-reader-binding
  namespace: observability
subjects:
  - kind: ServiceAccount
    name: default # Change if ServiceAccount is different
    namespace: observability
roleRef:
  kind: Role
  name: prometheus-pod-reader
  apiGroup: rbac.authorization.k8s.io